### ISSUE TITLE
Health section highlights

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#443] opened 2016-09-15 11:52 UTC
On the place pages, the county in which the place is located should be highlighted in the health section. For example, for [Kemp Mill, MD](http://datausa.io/profile/geo/kemp-mill-md/#housing) Montgomery County should be highlighted

**Comment by davelandry** [comment] 2016-09-15 14:02
duplicate of #199

**Closed by davelandry** 2016-09-15 14:02 UTC
Labels: bug
