### ISSUE TITLE
Need to know units

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#290] opened 2016-03-11 15:29 UTC
Similar to other graph, I don't know what these number are 'per'. Are they per 100,000?
http://beta.datausa.io/profile/geo/united-states/
![image](https://cloud.githubusercontent.com/assets/3857364/13706700/30819c8c-e774-11e5-9ca7-782526b573ce.png)

**Comment by danielbyler** [comment] 2016-03-11 15:30
Same goes for crime and safety chart

**Comment by davelandry** [comment] 2016-03-11 17:18
closed as a duplicate of #287

**Closed by davelandry** 2016-03-11 17:18 UTC
