### ISSUE TITLE
Measure Descriptions on Maps

### ISSUE THREAD

**Issue by ecischke** [DataUSA/datausa-site#536] opened 2017-04-24 18:34 UTC
In general, it would be very useful to include a brief description of each measure in the gray bar on the left, perhaps underneath or above the where the Dataset and Source are noted.  Currently, users must link back to source data to research specific measure definitions. 

https://datausa.io/map/?level=state&key=premature_death  >> this measure does not make sense as currently reported (years of potential life lost per 100,000 people)
https://datausa.io/map/?level=state&key=avg_age_ft,avg_age_ft_moe >> what does this mean? Need to clarify description or omit
https://datausa.io/map/?level=state&key=avg_age_pt,avg_age_pt_moe >> what does this mean?  Need to clarify description or omit

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment] 2017-04-27 15:43
Totally agree, prioritizing this for sunbird and closing as a duplicate of #445

**Closed by davelandry** 2017-04-27 15:43 UTC
