### ISSUE TITLE
Need to add menu option for 'View API URL' to all visualizations

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#593] opened 2017-06-12 21:52 UTC
Somehow this dropped out of 2.0.  THis was one of the best features of 1.0.  You could either change the menu icon which says 'view data' to read 'view data and API URL' or you could add a separate icon which says 'See API Call'.

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment] 2017-06-13 21:39
The API link is still available when clicking "view data" (duplicate of #546)

**Closed by davelandry** 2017-06-13 21:39 UTC
