### ISSUE TITLE
CSV generator not working on map

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#543] opened 2017-04-24 20:25 UTC
Reference this map on the original site:
https://datausa.io/map/?level=state&key=income_below_poverty,income_below_poverty_moe,pop_poverty_status,pop_poverty_status_moe

### Expected Behavior

When I choose options -> download -> CSV, instead of CSV I get a json file.  

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment] 2017-04-26 23:08
Duplicate of #444, prioritizing fix.

**Closed by davelandry** 2017-04-26 23:08 UTC
