### ISSUE TITLE
Data Quality Question

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#774] opened 2018-11-29 16:02 UTC
https://joshua-tree.datausa.io/visualize?groups=0-z7J78&measure=Z2ny7rj

2017 and 2018 show identical graduation rates. Based on the prior variability in the data, this doesn't seem possible. Is this data correct?

![image](https://user-images.githubusercontent.com/3857364/49234542-3bf84280-f3c6-11e8-839a-30513c2e4e05.png)

**Comment by davelandry** [comment] 2018-11-30 20:36
duplicate of https://github.com/DataUSA/datausa-site/issues/771

**Closed by davelandry** 2018-11-30 20:36 UTC
