### ISSUE TITLE
Need consistent scale on hospital care comparison charts

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#584] opened 2017-06-12 21:17 UTC
For example, comparing these two counties, you need consistent scales:
http://sunbird.datausa.io/profile/geo/baltimore-county-md/?compare=montgomery-county-md

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment] 2017-06-13 21:23
duplicate of #522

**Closed by davelandry** 2017-06-13 21:23 UTC
