### ISSUE TITLE
formatting very small numbers

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#311] opened 2016-03-14 21:40 UTC
Is this supposed to be possible?

http://beta.datausa.io/profile/naics/611M1/

![image](https://cloud.githubusercontent.com/assets/3857364/13760904/d4d2c2fe-ea0b-11e5-8160-cd98d452440d.png)

**Comment by davelandry** [comment] 2016-03-14 21:43
the actual values aren't zeros, just very small. the stricter number formatting I put in for the last release isn't allowing the decimal places to show

**Comment by davelandry** [comment] 2016-03-16 15:29
closed as a duplicate of #288

**Closed by davelandry** 2016-03-16 15:29 UTC
Labels: bug
