### ISSUE TITLE
CSV doesn't create properly

### ISSUE THREAD

**Issue by danielbyler** [DataUSA/datausa-site#528] opened 2017-04-21 17:54 UTC
When I am at https://datausa.io/map/?level=county&key=poor_or_fair_health in Chrome and click 'download CSV' I get poorly rendered output it's not a CSV (looks more like a failed JSON parse)

When opening, Excel lodges the error:

This message can appear due to one of the following:
The file contains more than 1,048,576 rows or 16,384 columns. To fix this problem, open the source file in a text editor such as Microsoft Word. Save the source file as several smaller files that conform to this row and column limit, and then open the smaller files in Microsoft Excel. If the source data cannot be opened in a text editor, try importing the data into Microsoft Access, and then exporting subsets of the data from Access to Excel.
The area that you are trying to paste the tab-delineated data into is too small. To fix this problem, select an area in the worksheet large enough to accommodate every delimited item.
Notes
Excel cannot exceed the limit of 1,048,576 rows and 16,384 columns.
By default, Excel places three worksheets in a workbook file. Each worksheet can contain 1,048,576 rows and 16,384 columns of data, and workbooks can contain more than three worksheets if your computer has enough memory to support the additional data.

**Comment by davelandry** [comment] 2017-04-26 23:08
Duplicate of #444, prioritizing fix.

**Closed by davelandry** 2017-04-26 23:08 UTC
Labels: bug
