### ISSUE TITLE
employment by occupation and employment by industry use pums but dont mention substituions?

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#804] opened 2019-01-31 22:04 UTC
<img width="1131" alt="screen shot 2019-01-31 at 5 02 12 pm" src="https://user-images.githubusercontent.com/87581/52088511-1203fd80-257a-11e9-8192-f30e30985109.png">

eg. `/profile/geo/somerville-ma#tmap_ind_num_emp` and `/profile/geo/somerville-ma#tmap_occ_num_emp` should reference that it's using the PUMA `Somerville & Everett Cities PUMA, MA`

**Comment by cnavarreteliz** [comment] 2019-01-31 22:16
This bug is related with #798

**Comment by davelandry** [comment] 2019-02-01 16:38
duplicate of #798

**Closed by davelandry** 2019-02-01 16:38 UTC
Labels: bug
