### ISSUE TITLE
Need better legend on 'Age By Nativity' chart, demographics section, location profile

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#329] opened 2016-03-21 14:21 UTC
No labels on legend, can't tell what the colors mean, eg:

<iframe width="360px" height="240px" src="http://beta.datausa.io/profile/geo/virginia/demographics/age_nativity?viz=True" frameborder="0" ></iframe>

**Comment by davelandry** [comment] 2016-03-21 16:49
duplicate of #321

**Closed by davelandry** 2016-03-21 16:49 UTC
