### ISSUE TITLE
Need notes or tooltips for definitions of menu items on map

### ISSUE THREAD

**Issue by pviechnicki** [DataUSA/datausa-site#535] opened 2017-04-24 13:27 UTC
Reference: the map view, especially the health indicators section:
http://sunbird.datausa.io/map/?level=county&key=adult_obesity

### Expected Behavior

Our users are telling us they don't know the meaning of many of the menu items, such as the following:
“Diabetic monitoring” 
“food insecurity” (I understand this but would like to know more about what this measures), 
“graduate growth” (is this college? Growth from the previous year or when?)
“preventable hospital stays” (what does preventable mean?) 
“years of potential life lost”
“years of potential life lost age-adjusted”

Could someone pull definitions from the source, and put these in a popup or tool-tip visible from the menu, so people can understand what they're looking at?

### Steps to Reproduce (for bugs)

1.
2.
3.

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment] 2017-04-27 15:43
Totally agree, prioritizing this for sunbird and closing as a duplicate of #445

**Closed by davelandry** 2017-04-27 15:43 UTC
